version: "3"
services:
  mysql_db:
    container_name: db_spring
    image: mysql
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: school
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
        - "3306:3306"
    volumes:
        - ./db_data:/var/lib/mysql